node {

    checkout scm

    env.DOCKER_API_VERSION="1.23"
    
    sh "git rev-parse --short HEAD > commit-id"

    appName = "webapp"
    registryHost = "test-image.itccloud.local:5000"
    imageName = "${registryHost}:${appName}"
    env.BUILDIMG=imageName

    stage "Build"
    
        sh "docker build -t ${imageName} -f  application/Dockerfile application"
    
    stage "Push"

        sh "docker push ${imageName}"

    stage "Deploy"

        kubernetesDeploy configs: "applications/k8s/*.yml"

}
